apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trialport
  labels: 
    app: trial
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        # We advise you to build, push and use your own image, instead of using instructor's image.
        image: ghcr.io/jasonsmithio/trial:v1
        ports:
        - containerPort: 8080
          name: trialport
          protocol: TCP
        imagePullPolicy: Always
        env:
        - name: JAEGER_AGENT_HOST
          value: simplest-agent.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
  labels:
    app: trial
spec:
  selector:
    app: trial
  ports:
    - name: trial
      port: 8082
      targetPort: trialport
      protocol: TCP
  type: LoadBalancer

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial
  namespace: monitoring
  labels:
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      release: prometheus
  endpoints:
  - port: trial
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default