{
 "title": "33",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{job=\"backend-service\"})\n      or\n    (0 * sum_over_time(up{job=\"backend-service\"}[1d]))\n  )[1d:5m]\n)"
    }
   ]
  },
  {
   "title": "measure 40X, 50X error code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(\n  flask_http_request_duration_seconds_count{status=\"405\"}[30s]\n)"
    },
    {
     "expr": "rate(\n  flask_http_request_duration_seconds_count{status=\"500\"}[30s]\n)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(\n  process_cpu_seconds_total{job=\"backend-service\"}[30s]\n)"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(\n  flask_http_request_total[1m]\n)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"backend-service\"}"
    }
   ]
  },
  {
   "title": "errors per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_count{status!=\"200\"}[30s]\n  )\n)"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(\n  flask_http_request_duration_seconds_sum{status=\"200\"}[30s]\n)\n /\nrate(\n  flask_http_request_duration_seconds_count{status=\"200\"}[30s]\n)"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(\n  flask_http_request_duration_seconds_count{status=\"200\"}[30s]\n)"
    }
   ]
  }
 ]
}