{
 "title": "KPIs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU consumption by all services",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{}[30s])) * 100"
    }
   ]
  },
  {
   "title": "Memory consumption by all services",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{}) / 8000000000 * 100"
    }
   ]
  },
  {
   "title": "Uptime for Frontend and Backend services in the last 24 hrs.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (increase(up{job=~\"backend-service|frontend-service\"}[24h]) ) *100"
    }
   ]
  },
  {
   "title": "Successful requests under 250 msecs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.25\"}[30s]) / ignoring (le) increase(flask_http_request_duration_seconds_count{status=\"200\"}[30s]) ) * 100"
    }
   ]
  },
  {
   "title": "P90 response time (msecs) for successful requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": " avg( histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[30s])) ) * 1000"
    }
   ]
  },
  {
   "title": "Number of Exceptions (500 errors)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "flask_http_request_exceptions_total{service=\"backend-service\"}\n"
    }
   ]
  },
  {
   "title": "uptime for frontend and backend services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 25 },
   "targets": [
    {
     "expr": "up{job=~\"backend-service|frontend-service\"}"
    }
   ]
  }
 ]
}