{
 "title": "Up_404_500",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Uptime for Frontend and Backend services in the last 24 hrs.",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (increase(up{job=~\"backend-service|frontend-service\"}[24h]) ) *100"
    }
   ]
  },
  {
   "title": "Number of 4XX errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{container=\"frontend\",status=\"404\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Number of 5XX errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{container=\"backend\",status=\"500\"}[5m]))\n"
    }
   ]
  }
 ]
}