{
 "title": "Uptime and Requests",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Up time frontend + backend",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"backend-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{job=~\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx, 5xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{container=\"frontend\",status=\"404\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(flask_http_request_total{container=\"backend\",status=\"410\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(flask_http_request_total{container=\"backend\",status=\"500\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ALL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "instance:node_cpu:rate:sum{instance=\"192.168.49.2:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consume by ALL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{})/8000000000*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger Trace Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "service": "backend" }
   ]
  }
 ]
}