{
 "title": "Watchmen Uptime Dashboard",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Service Name",
    "query": "SELECT name from service_status"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT b.name, b.first_ping, COALESCE (a.duration, 0) AS duration\nFROM (SELECT name, sum(duration)/10 AS duration, max(last_outage) as last_outage FROM service_back WHERE last_outage > $__timeFrom() GROUP BY name) AS a \nRIGHT JOIN service_status AS b ON a.name=b.name\n"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "singlestat",
   "description": "Change Service Name Variable, to check uptime for each service",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ((($__unixEpochTo()-$__unixEpochFrom())::BIGINT - AVG(COALESCE (a.duration, 0)/1000::float))/($__unixEpochTo()-$__unixEpochFrom())::BIGINT)*100 AS duration\nFROM (SELECT name, sum(duration) AS duration FROM service_back WHERE name IN ($name) AND $__timeFilter(last_outage) GROUP BY name ) AS a \nRIGHT JOIN service_status AS b ON a.name=b.name\n\n"
    }
   ]
  },
  {
   "title": "Incident Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"last_outage\",'1s'),\n  last_outage + CONCAT(SUM(DURATION), ' ms')::interval + interval '7 hour'  AS \"Resolved Time\",\n  name as \"Service Name\",\n  sum(\"duration\")/10 as \"duration\"\nFROM service_back\nWHERE $__timeFilter(\"last_outage\") AND name IN ($name)\nGROUP BY time, name,last_outage\nORDER BY time"
    }
   ]
  }
 ]
}